Add initial project template
EPFLSWENT2024G1/partagix pull request #1
Opened 2024-03-18 10:46 UTC by KassFlute

Add the initial project template from CS-311

2024-03-18 12:17 UTC, Valentin889 requested changes
Pour passer le solar ils veulent un truc de ce type dans le gradle
```
<application
    android:usesCleartextTraffic="false">
</application>
```
Le reste semble être une bonne base pour commencer à travailler

2024-03-18 15:14 UTC, KassFlute commented
Something with sonar still fail in the CI, maybe we have to setup a SONAR token somewhere

2024-03-18 19:22 UTC, Valentin889 commented
Sur une autre branche j'ai réussi à faire passer le CI en ajoutant ça : 
```
sonar.gradle.skipCompile=true
```
Dans gradle.properties

2024-03-19 20:42 UTC, KassFlute commented
Pourquoi sonarcloud post quand même son quality report dans la PR sans être dans ci.yml ??

2024-03-19 20:51 UTC, KassFlute commented
Bon,
si je comprends bien [ce forum](https://community.sonarsource.com/t/sonarcloud-task-fails-because-of-ci-analysis-and-auto-analysis-running/22937/3), on a l'automatic analysis activée donc on devrait pas avoir en même temps une action dans la CI.

2024-03-20 06:33 UTC, Valentin889 approved these changes
Tout bon pour moi

2024-03-20 06:33 UTC, merged

2024-03-22 17:27 UTC, TruddyTheDuddi commented
Hey, we expect you to write the comments/reviews in English! :) @Valentin889 @KassFlute