MB - ItemViewModel.kt implementation
EPFLSWENT2024G1/partagix pull request #23
Opened 2024-03-28 17:45 UTC by Mass-14

ItemViewModel.kt implemented on the example of InventoryViewModel.kt

2024-03-28 18:04 UTC, LozanoCyrielle requested changes
You return the first item of the list not the one we are searching for
Maybe use the item id to find the one we are searching for
Also you there is no function to create/ to add an item to the database

2024-03-29 09:57 UTC, Valentin889 commented
The get item function needs an item id for it to make sense
You need a function to add a new item (this need an update in the db class too)
and a function to edit an existing item which also ned an update in the db class

2024-03-29 16:10 UTC, Valentin889 commented
That's the idea for update Item you got it (:
It's important to format before you push because first it will pass the CI and also it's way easier to see you change you actually made, review the diff like this is way harder

2024-03-29 16:21 UTC, Mass-14 commented
Thank you @Valentin889, I thought the format was needed only when adding new files...

2024-03-30 12:45 UTC, Valentin889 commented
1. The createItem function in db should take an item as a parameter; otherwise, the information you're going to input into the database won't make sense.

2. Instead of that, I would rather take the ID of an item as a parameter or the entire item itself, and filter based on that, not with the UI.
```
  private fun getItem() {
    viewModelScope.launch {
      database.getItems {
        for (i in it) {
          if (i.id == _uiState.value.item.id) {
            update(i)
          }
        }
      }
    }
  }
  ```
3. Be careful with the names, like update and updateItem, it's not clear what the difference is.
4. Some functions in the view model are public so that the UI can use them. If everything is private, the view model doesn't make much sense. Try to think about the use cases of each function (which class will use them and for what purpose). It will help to understand which parameter to take and properly name the functions.

2024-03-31 13:22 UTC, LozanoCyrielle commented on app/src/main/java/com/android/partagix/model/ItemViewModel.kt
> +
Maybe more edit item instead of save item

2024-03-31 13:23 UTC, LozanoCyrielle approved these changes
I would just maybe rename the saveItem into Edit item but except that, everything seems good :))

2024-04-01 09:20 UTC, Valentin889 approved these changes
Seems good to me

2024-04-02 22:26 UTC, merged