loan request UI fix
EPFLSWENT2024G1/partagix pull request #255
Opened 2024-05-17 21:13 UTC by skyrag

put the ui of the loan request and the item view creat and edit up to figma because all those screen use the same screen so everything is change at the same time

2024-05-18 16:16 UTC, KassFlute requested changes
Nice PR, I found some issues that should be addressed before merging to have nice loan requests

### UI notes:
- Not having the borrow item button on our own items is great but I think it looks strange to just hide the button. (see below)
<img width="329" alt="Capture d’écran 2024-05-18 à 17 43 04" src="https://github.com/EPFLSWENT2024G1/partagix/assets/74629729/c9c9f315-ac0f-4778-8203-28de42269c1b">

Maybe we could just make the button unclickable and tint it gray or something like this.

- I also feel that the font is really small on the view item screen (see code notes). 

### Code notes:
- Many text styles/colors/fonts are set but not by using the text style in the theme. These should be used. 
- Same for the colors, colors from the theme should be used. Now in darktheme a big part of the loan request design is unreadable/unusable. 
- The Loan screens should be tested in dark mode and on the small phone for the padding.
- Good code coverage

2024-05-18 17:06 UTC, skyrag commented on app/src/main/java/com/android/partagix/ui/screens/BorrowScreen.kt
> +                    readOnly = true)
i understood it as the description of the item and i don't understand why the description of the item could be change by the person borrowing it

2024-05-19 08:20 UTC, KassFlute commented on app/src/main/java/com/android/partagix/ui/screens/BorrowScreen.kt
> +                    readOnly = true)
I thought it was a description of the loan.

2024-05-19 08:34 UTC, KassFlute requested changes
- The grayed out borrow button on our own items is great
- The paddings are good on different phone sizes

But the colors are still wrong. You used theme's colors and that's great but you need to test with the dark mode enabled. See below the loan screen in dark mode that is strange.
<img width="360" alt="Capture d’écran 2024-05-19 à 10 32 21" src="https://github.com/EPFLSWENT2024G1/partagix/assets/74629729/95eed2f8-6927-47ba-8a04-15662825bf28">

2024-05-19 15:32 UTC, KassFlute approved these changes
There is still some colors that are wrong. For example you use "onPrimary" for buttons that are on the background. "onPrimary" should be used for elements that are on the color "primary".
But it's ok we can make future other tasks to change the colors.

2024-05-19 15:33 UTC, KassFlute commented on app/src/main/java/com/android/partagix/ui/screens/BorrowScreen.kt
> +                          contentColor = MaterialTheme.colorScheme.background,
still wrong but more acceptable as it's readable in both modes

2024-05-19 20:03 UTC, merged