Fix "Author" field
EPFLSWENT2024G1/partagix pull request #284
Opened 2024-05-21 17:00 UTC by KassFlute

All 'author' fields are replaced by 'owner'. The new 'owner' field is then made clickable to redirect to the corresponding profile page

2024-05-22 12:32 UTC, Mass-14 requested changes
Don't worry for the coverage, this will be fixed with the new App.kt test, these low scores are only a consequence of SonarCloud illogical way to count the coverage :( .
Can you please add javadocs on public functions of UserViewModel, we have very close functions hence it is necessary.

The renaming Author to Owner is great, however the functionality of going to the account screen is not working when I am not the owner.

What behaviour I see is the following : 
1. click on an item on the loan screen
2. click on the owner's name 
3. I am redirected to my account the owner's data for few frames (like screenshot below) before it reloads and takes my data.

The behaviour at this point should be the following : 
- I am redirected to a new screen with the owner's data, without the _edit profile_ button. 
- The top level destination of this screen should not be "account" since it is not my account
 
![image](https://github.com/EPFLSWENT2024G1/partagix/assets/126057141/501e14be-705a-4bf0-856a-1cef4bf72192)

2024-05-22 13:32 UTC, Patrick-Pataky requested changes
Indeed, 50% of coverage is low. Part is due to missing tests in App.kt, but also missing tests for the `UserViewModel`.

I think you can easily add tests for the untested functions in this view model. Indeed, your PR is strongly connected to the user view model, so it is not irrelevant to add them.
- Note: the untested functions are really small & simple. Adding the tests won't take you more than 20min ^^

2024-05-22 13:32 UTC, Patrick-Pataky commented on app/src/main/java/com/android/partagix/model/UserViewModel.kt
> +  }
To easily improve coverage, you can add a test for this function (should be very easy to test)

2024-05-22 16:07 UTC, KassFlute commented
I said in my comment that I'll test the view model @Patrick-Pataky.
@Mass-14 For mysterious reasons when I tested myself to look at other's profile it was working but I see why it couldn't work.  And anyways, it makes way more sense to have a different screen to display other's profile. It also makes sense to have a second viewModel for this new screen. I did this in the last commits that you can check if you want. I'll ask for review after adding tests for this.

2024-05-23 15:04 UTC, Mass-14 requested changes
![image](https://github.com/EPFLSWENT2024G1/partagix/assets/126057141/c91f2b99-4a25-4a69-bea7-7ebfd6d233a5)
Remarks : 
- the text in the top bar should be fixed to one line (you can use `maxLines = 1,` and  `overflow = TextOverflow.Ellipsis,` as Text arguments.
- There should be a big spacer (min 20.dp) at on top of the image 
- As well as a small padding (~8.dp) below the image.

![image](https://github.com/EPFLSWENT2024G1/partagix/assets/126057141/cc6b936e-4459-4da0-9567-3dd7cc027a00)

2024-05-23 15:44 UTC, KassFlute commented
Thanks for your review, I implemented your good suggestions.

2024-05-23 16:45 UTC, Patrick-Pataky approved these changes
It seems that you obtained enough coverage. Good job

2024-05-23 17:01 UTC, Mass-14 approved these changes
Great work :)

2024-05-23 17:01 UTC, merged