cleaning some preview and deleting the duplicate list
EPFLSWENT2024G1/partagix pull request #93
Opened 2024-04-16 08:42 UTC by skyrag

2024-04-18 14:32 UTC, Mass-14 requested changes
![image](https://github.com/EPFLSWENT2024G1/partagix/assets/126057141/28fa27f0-3990-47e9-9769-3a6f60528fc2)

The item number of each field brakes the coherence in the UI when it has 2 digits (which go in column and not on the same line). Also this item number field is clickable, it shouldn't, and finally it should have the same padding with respect with the right edge, as the textfields.

ItemUi.kt : 
- the value Date (line 45) shouldn't be with a capital D
- the value time (line 51) in unused, it should be either commented with a explanation of the potential use, or deleted.

ItemList.kt : I just learned that the modifier argument of a composable function should be the first of the arguments. It's not a big deal but wanted to share this :)

InventoryScreen.kt : unused import line 22

InventoryViewModel.kt : 
- the private function getItems() isn't used, it should be commented (if potentially useful in the future)
- value users is unused (line 164), commented or deleted
- lots of non conventional naming (camelCase not respected, follow your IDE recommendations) 

Otherwise functional correctly, good job !

2024-04-18 14:45 UTC, skyrag commented
thanks for the feedback, concerning the item number it doesnt appear like this on my phone so, i'm surprised but i'll look into it and concerning the fact that it is clickable it is suppose to be like that because for the loan part of the app we want to have a clickable text. Instead of the number of items it would be a see all and because we use the same function to show both it is just a clickable that does nothing. But if you have another idea on how to do it, we can talk about it

2024-04-18 15:01 UTC, Mass-14 commented
In order for this field to be clickable only when needed (see all), the clean solution would be to have an additional parameter in the ItemListColumn composable : `clickableCorner: Boolean = false,` with a ternary operator on the modifier (line 63) to give the onClickCorner action only if clickableCorner is True.

2024-04-18 17:30 UTC, Mass-14 requested changes
ItemUi.kt :
- unused import (line 16)

ItemListSeparator : 
- misleading `isClickable` parameter name, it should be contain at least the word _clickable_ and _corner_, since there is onClick and onClickCorner.
- additionally some the naming convention isn't respected in two parameters (line 35 and 38)
- the JavaDoc needs to be updated

InventoryViewModel :
- the update function (line 111) isn't called anmyore

InventoryScreen :
- line 106 and 121, the TODO should be removed since this is going to remain empty

2024-05-02 22:31 UTC, Mass-14 commented on app/src/main/java/com/android/partagix/ui/screens/InventoryScreen.kt
The line 73 exceeds the 80 chars width limit, it should be split on two lines.

2024-05-02 22:55 UTC, Mass-14 commented on app/src/main/java/com/android/partagix/ui/components/ItemList.kt
> +  println(itemList.size)
line 39,40,41 : warning you forgot some println

2024-05-02 23:30 UTC, Mass-14 reviewed
All changes are minor, overall great work !

2024-05-02 23:30 UTC, Mass-14 commented on app/src/main/java/com/android/partagix/model/InventoryViewModel.kt
lots of comments not relevant anymore, and prints that should be deleted

2024-05-02 23:30 UTC, Mass-14 commented on app/src/androidTest/java/com/android/partagix/inventory/InventoryTest.kt
Empty test on line 96

2024-05-02 23:48 UTC, Mass-14 submitted a review, later dismissed

2024-05-03 19:17 UTC, Patrick-Pataky approved these changes
Great job ! It's finally time to merge it :)

2024-05-03 19:17 UTC, merged